export const observerTopics = (function () {
  const BARCODE_TOPIC = "BARCODE_NEW_PRODUCT_SCANNED";
  const CARD_READER_TOPIC = "MAGNETIC_CARD_READ";
  const ESIGNATURE_COORDINATES_TOPIC = "COORDINATES_ESIGNATURE_RECEIVED";
  const ESIGNATURE_IMAGE_TOPIC = "IMAGE_ESIGNATURE_RECEIVED";

  return {
    BARCODE_TOPIC,
    CARD_READER_TOPIC,
    ESIGNATURE_COORDINATES_TOPIC,
    ESIGNATURE_IMAGE_TOPIC,
  };
})();
