export const OBSERVER_TOPICS = Object.freeze({
  BARCODE_TOPIC: "BARCODE_NEW_PRODUCT_SCANNED",
  CARD_READER_TOPIC: "MAGNETIC_CARD_READ",
  ESIGNATURE_COORDINATES_TOPIC: "COORDINATES_ESIGNATURE_RECEIVED",
  ESIGNATURE_IMAGE_TOPIC: "IMAGE_ESIGNATURE_RECEIVED",
  THEME_CHANGED: "APP_THEME_CHANGED",
  BUTTONS_COLOR_CHANGED: "BUTTONS_COLOR_CHANGED",
});
